server:
  port: 8085

spring:
  application:
    name: notification

  datasource:
    url: jdbc:mysql://localhost:3308/notification_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
