package com.erumpay.notification.domain.enums;

public enum NotificationType {
    PAYMENT_COMPLETED,
    PAYMENT_CANCELED,
    CARD_REGISTERED,
    CARD_DELETED,
    REMOTE_REQUESTED,
    REMOTE_APPROVED,
    REMOTE_REJECTED,
    REMOTE_COMPLETED,
    DUTCHPAY_INVITED,
    DUTCHPAY_CONFIRMED,
    DUTCHPAY_1ST_TIMEDOUT,
    DUTCHPAY_2ST_TIMEDOUT,
    DUTCHPAY_COMPLETED,
    AUTH_FRIEND
}
